# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('hide', models.BooleanField(db_index=True, default=False, verbose_name='\u96b1\u85cf\u7559\u8a00')),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('response', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['date_time'],
                'permissions': (('can_comment', 'Can comment'),),
            },
        ),
    ]
