# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='response',
        ),
    ]
