# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messages_board', '0002_auto_20160301_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
    ]
