# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_board', '0003_auto_20160301_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
