# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_board', '0006_post_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hide',
        ),
    ]
