# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 09:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, upload_to=b'blog/images/%Y/%m/%d')),
                ('cropping', image_cropping.fields.ImageRatioField(b'images', '1920x650', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('author', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('content_upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b'', null=True, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x85\xa7\xe5\xae\xb9')),
                ('create_time', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('modify_time', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Categories'),
        ),
    ]
